Trog\Bundle\Article\Document\Page:
    definitions:
        frontend:
            uri_schema: /page/{title}
            defaults:
                _controller: trog_content_type.controller.view:defaultAction

    token_providers:
        title: [content_method, { method: getTitle } ]

Trog\Bundle\Article\Document\Post:
    definitions:
        frontend:
            uri_schema: /post/{title}
            defaults:
                _controller: trog_content_type.controller.view:defaultAction

    token_providers:
        title: [content_method, { method: getTitle } ]

Trog\Bundle\Article\Document\Example:
    definitions:
        frontend:
            uri_schema: /example/{title}
            defaults:
                _controller: trog_content_type.controller.view:defaultAction

    token_providers:
        title: [content_method, { method: getTitle } ]

