cmf_routing_auto:
    persistence:
        phpcr:
            enabled: true
            route_basepath: /trog/routes

    adapter: doctrine_phpcr_odm
    mapping:
        resources:
            path: %kernel.root_dir%/config/cms/cmf_routing_auto_mapping.yml
