cmf_resource:
    repositories:
        default:
            type: doctrine_phpcr_odm
            basepath: /sycms
        filesystem:
            type: filesystem
            base_dir: %kernel.root_dir%
    description:
        enhancers:
            - doctrine_phpcr_odm
            - sylius_resource
            #- sycms_text_editor
