imports:
    - { resource: resources.yml }
    - { resource: psi_content_type.yml }
    - { resource: psi_description.yml }
    - { resource: symfony_cmf.yml }
    - { resource: trog_resource_browser.yml }
    - { resource: "@TrogAdminBundle/Resources/config/main.yml" }
