cmf_resource:
    repositories:
        default:
            type: doctrine_phpcr_odm
            basepath: /trog/posts
        pages:
            type: doctrine_phpcr_odm
            basepath: /trog/pages
        media:
            type: doctrine_phpcr_odm
            basepath: /trog/media
