cmf_resource:
    repositories:
        default:
            type: doctrine_phpcr_odm
            basepath: /sycms
        filesystem:
            type: filesystem
            base_dir: %kernel.root_dir%
        media:
            type: doctrine_phpcr_odm
            basepath: /sycms/posts
    description:
        enhancers:
            - doctrine_phpcr_odm
            - text_editor
