cmf_resource:
    repositories:
        default:
            type: doctrine_phpcr_odm
            basepath: /sycms/posts
        pages:
            type: doctrine_phpcr_odm
            basepath: /sycms/pages
        media:
            type: doctrine_phpcr_odm
            basepath: /sycms/media
