trog_resource_browser:
    browsers:
        default:
            default_repository: pages
            repositories:
                - default
                - pages
                - media
                - files
            enable_move: true
            enable_item_actions: true
            columns: 4
            template: "@TrogAdmin/ResourceBrowser/index.html.twig"

        selector:
            default_repository: media
            repositories:
                - media
                - pages
                - files
            enable_move: false
            enable_item_actions: false
            columns: 3
            template: "@TrogResourceBrowser/browser.html.twig"
