trog_resource_browser:
    browsers:
        default:
            default_repository: pages
            repositories:
                - default
                - pages
                - media
            enable_move: true
            enable_item_actions: true
            columns: 4
            template: "@TrogAdmin/ResourceBrowser/index.html.twig"
#        media_overlay:
#            default_repository: media
#            repositories:
#                - media
#            enable_move: false
#            enable_item_actions: false
#            columns: 2
#            template: "@TrogResourceBrowser/browser.html.twig"
