trog_content_type_crud_edit:
    path: /edit/{agent}/{identifier}
    defaults:
        _controller: trog_content_type.controller.crud:edit
    requirements:
        path: .*


trog_content_type_crud_create_as_child:
    path: /{agent}/{parent_identifier}/{type}/createAsChild
    defaults:
        _controller: trog_content_type.controller.crud:createAsChild
