cms:
    resource: "resources.yml"

tree:
    resource: "@SycmsColumnBrowserBundle/Resources/config/routing.xml"
    prefix: /admin
    defaults:
        repository: default
        template: ::column_browser.html.twig

text_editor:
    resource: "@SycmsTextEditorBundle/Resources/config/routing/main.yml"
    prefix: /admin/text-editor
    defaults:
        layout: ::text_editor.html.twig
