page:
    resource: |
        alias: acme.page
        grid: acme_page
        redirect: update
        templates: CmfAdminBundle:Crud
        except: [ 'show ']
    type: sylius.resource
    prefix: /admin

post:
    resource: |
        alias: acme.post
        grid: acme_post
        templates: CmfAdminBundle:Crud
        redirect: update
        except: [ 'show ']
    type: sylius.resource
    prefix: /admin

post_folder:
    resource: |
        alias: acme.post_folder
        templates: CmfAdminBundle:Crud
        redirect: update
        except: [ 'show ']
    type: sylius.resource
    prefix: /admin

page_folder:
    resource: |
        alias: acme.page_folder
        templates: CmfAdminBundle:Crud
        redirect: update
        except: [ 'show ']
    type: sylius.resource
    prefix: /admin

