sycms_repository_browser:
    resource: "@SycmsResourceBrowserBundle/Resources/config/routing.xml"
    prefix: /admin
    defaults:
        template: "@SycmsAdmin/ResourceBrowser/index.html.twig"

text_editor:
    resource: "@SycmsTextEditorBundle/Resources/config/routing/main.yml"
    prefix: /admin/text-editor
    defaults:
        template: "@SycmsAdmin/TextEditor/index.html.twig"

content_type_crud:
    resource: "@SycmsContentTypeBundle/Resources/config/routing/main.yml"
    prefix: /admin/content
    defaults:
        template: "@SycmsAdmin/ContentType/Crud/edit.html.twig"
